name: 'Build for ESP32'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build grblHAL
      uses: docker://espressif/idf:release-v4.3
      with:
        entrypoint: /opt/esp/entrypoint.sh
        args: bash -c "idf.py build"
    - name: Upload all .bin files
      uses: actions/upload-artifact@v4
      with:
      name: firmware-binaries
       path: build/**/*.bin
